[server]
  host = "localhost"
  port = 9000
  url = "http://geo.kralidis.ca/go-wfs/"
  mimetype = "application/json; charset=UTF-8"
  encoding = "utf-8"
  language = "en-US"
  pretty_print = true
  limit = 10

[logging]
  level = "INFO"
  #logfile = "/tmp/go-wfs.log"

[metadata]
  [metadata.identification]
    title = "go-wfs"
    description = "go-wfs is a Go server implementation of OGC WFS 3.0"
    keywords = [ "geospatial", "features", "collections", "access" ]
    keywords_type = "theme"
    fees = "None"
    accessconstraints = "None"
    [metadata.provider]
      name = "Organization Name"
      url = "https://github.com/go-spatial/go-wfs"
    [metadata.contact]
      name = "Lastname, Firstname"
      position = "Position Title"
      address = "Mailing Address"
      city = "City"
      stateorprovince = "Administrative Area"
      postalcode = "Zip or Postal Code"
      country = "Country"
      phone = "+xx-xxx-xxx-xxxx"
      fax = "+xx-xxx-xxx-xxxx"
      email = "you@example.org"
      url = "http://example.org"
      hours = "Hours of Service"
      instructions = "During hours of service.  Off on weekends."
      role = "pointOfContact"

[providers]
  data = "test-data/athens-osm-20170921.gpkg"
